[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tacoeditor"
version = "0.1.0"
description = "A beatmap editor for osu!taiko and Taco"
requires-python = ">=3.8"
dependencies = [
    "PyGObject",
    "cffi"
]

[project.scripts]
tacoeditor = "tacoeditor.main:main"
