[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tacoeditor"
version = "0.1.0"
description = "A beatmap editor for osu!taiko and Taco"
requires-python = ">=3.8"
dependencies = [
    "PyGObject"
]

[project.gui-scripts]
tacoeditor = "tacoeditor.main:main"
